---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/1/18 上午 04:26
---

---@class Vec3
local M={}

local vec3 = {
    x,
    y,
    z,
}

function M:vectorTo(vec3)

end

function M:normalize()

end

function M:dot(vec3)

end


