---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2024/1/17 下午 04:58
---

fuckyou = 0

function main()
    print("ffff")
end

print("fafafa")


local a = luajava.newInstance( "net.minecraft.world.phys.Vec3", 1.0,1.0,1.0)
local aClass = luajava.newInstance( "net.minecraft.world.phys.Vec3", 1.0,1.0,1.0)
print(a)

print(aaa)

function fff(Vec3)
    print();
end